Add exit on error

diff --git a/gitm b/gitm
--- a/gitm
+++ b/gitm
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+# Exit on error
+set -o errexit
+
 usage() {
     echo """
 git-multi
